# Generated by Django 3.0.4 on 2020-05-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignages',
            name='resume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
