# Generated by Django 3.0.4 on 2020-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200509_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='documents',
            field=models.FileField(blank=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
