# Generated by Django 3.0.4 on 2020-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200510_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignages',
            name='pseudo',
            field=models.CharField(default='Anonyme', max_length=42),
        ),
        migrations.AlterField(
            model_name='temoignages',
            name='resume',
            field=models.CharField(max_length=100),
        ),
    ]
