# Generated by Django 3.0.4 on 2020-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200510_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
