# Generated by Django 3.0.4 on 2020-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200510_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'format',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lien', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ressource',
                'ordering': ['titre'],
            },
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Temoignages',
            new_name='Temoignage',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
