# Generated by Django 3.0.4 on 2020-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200511_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='nature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
