# Generated by Django 3.0.4 on 2020-05-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_ressource_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'article'},
        ),
        migrations.AlterModelOptions(
            name='temoignage',
            options={'ordering': ['date'], 'verbose_name': 'temoignage'},
        ),
    ]
