# Generated by Django 3.0.4 on 2020-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200511_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='Categorie',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['titre'], 'verbose_name': 'categorie'},
        ),
    ]
