# Generated by Django 3.0.4 on 2020-05-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200514_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['date'], 'verbose_name': 'categorie'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
    ]
