# Generated by Django 3.0.4 on 2020-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200514_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
